### PR TITLE
Refactor.

### PR DESCRIPTION
**Pull request by zoubin**
This pr introduces some big changes and a major version should be released.
- Add more tests.
- Redefine the way formatters can be configured.
  `progress` will only be valid when `ansi` is true,
  and `ansi` is no longer available for `markdown`.

### CODE REVIEW

**Comment by zoubin** [comment]
@Hypercubed 
I see that [tap-markdown](https://github.com/Hypercubed/tap-markdown/blob/master/bin/cmd.js) uses the `markdown` option as well as `ansi` and `progress`.
I am wondering in which cases they could all be true?

Also, I made some twists to the markdown output.
Any conflicts with what `tap-markdown` expects?

## With comments

# Tests
- ✔ sync [pass: 1, fail: 0, duration: 0ms]
- ✔ async [pass: 1, fail: 0, duration: 3ms]

# Summary
- duration: 3ms
- planned: 2
- assertions: 2
- pass: 2
- fail: 0

# Comments

```
# sync
Hello,

# async
world!
```

## With fails

# Tests
- ✔ pass [pass: 1, fail: 0, duration: 0ms]
- ✖ fail [pass: 0, fail: 1, duration: 0ms]
- ✖ pass and fail [pass: 1, fail: 1, duration: 3ms]

# Summary
- duration: 3ms
- planned: 4
- assertions: 4
- pass: 2
- fail: 2

# Fails

```
# fail
  ✖ should fail
    operator: ok
    expected: true
    actual:   false
    at: Test.<anonymous> (/Users/zoubin/usr/src/self/tap-summary/example/error.js:9:5)

# pass and fail
  ✖ should fail
    operator: ok
    expected: true
    actual:   false
    at: Test.<anonymous> (/Users/zoubin/usr/src/self/tap-summary/example/error.js:15:5)
```

**Comment by Hypercubed** [comment]
`tap-markdown` does only two things:

1) Sets the defaults to `--markdown --no-ansi --no-progress`
2) runs the result through `tidy-markdown`

I really don't see the benefit of ever setting `ansi` or `progress` on when the output is markdown.

What we could do is move `tap-summary/lib/markdown.js` to to the `tap-markdown` repo and remove the option from `tap-summary`.  `tap-markdown` then maintain it's own reporter and uses `tap-summary` internally.

**Comment by zoubin** [comment]
> What we could do is move tap-summary/lib/markdown.js to to the tap-markdown repo and remove the option from tap-summary

👍 Good idea!
I'm going to disable the markdown option in tap-summary, and make a pr to tap-markdown and move markdown.js there.

**Comment by Hypercubed** [comment]
👍

**Pull request merged**
